# Numpy

# Pacote para operações matemáticas que suportam análise estatística, análise de dados, inteligencia artificial, entre outros.

Numpy = Numerical Python

- Numpy trabalha com o conceito de Array e tem suporte a leitura de database;
- Disponibiliza diversas funções de cálculos e estátisticas;

Site: https://numpy.org

Intalação: pip install numpy

## Array Numpy

### Array numpy: É uma lista de dados de mesmo tipo.

Nomeclatura Oficial: ndarray
- 1-D array - array com 1 dimesão - vetor, lista
- 2-D array - array com 2 dimensões - matriz
- 3-D ou mais array - array com 3 dimensões - tensor

In [10]:
# Importando a biblioteca numpy

import numpy as np

In [11]:
 # Criando um array numpy

array_01 = np.array([2, 6, 5, 1, 55])
print(array_01)

[ 2  6  5  1 55]


In [13]:
# type() - é um função python para viaualizar o tipo de dado

print(type(array_01))

<class 'numpy.ndarray'>


## Propriedades

In [15]:
# dtype() - Imprime o tipo dos dados do array numpy

print(array_01.dtype)

int32


In [17]:
# shape() - dimensão e quantidade de elementos do array numpy

print(array_01.shape)

(5,)


In [22]:
# size() - Apenas a quantidade de elementos do array

array_01 = np.array([2, 6, 5, 1, 55])
print(array_01.size)

5


## Funções 

In [23]:
# cumsum() - gera um novo array numpy com a soma acumulada dos elementos

array_01 = np.array([2, 6, 5, 1, 55])
print(array_01.cumsum())

[ 2  8 13 14 69]


In [32]:
# arange() - Cria um array numpy seguindo a mesma lógica da função range()

array_01 = np.arange(2)
print(array_01)

[0 1]


In [33]:

array_01 = np.arange(10)
print(array_01)

[0 1 2 3 4 5 6 7 8 9]


In [31]:

array_01 = np.arange(2, 10)
print(array_01)

[2 3 4 5 6 7 8 9]


In [35]:

array_01 = np.arange(2, 10, 2)
print(array_01)

[2 4 6 8]


In [37]:
array_01 = np.arange(2, 10, 4)
print(array_01)

[2 6]


In [36]:
'''
linspace() - gera um array numpy que:
(1, 10, 4)
1 - Número inicial do intervalo
10 - Número final do intervalo
4 - Deve preencher o array com 4 elementos deste intervalo com o mesmo espaçamento entre eles.
'''

array_01= np.linspace(1, 10, 4)
print(array_01)

[ 1.  4.  7. 10.]


In [41]:
# equal() - compara os elementos de um array numpy, resultando em um array de booleanos

array_02 = np.array([1,4,7,4])
array_03 = np.array([2,4,7,4])
print(np.equal(array_02, array_03))

[False  True  True  True]


In [42]:
# array_equal() - compara se o array é igual ao outro

array_02 = np.array([1,4,7,4])
array_03 = np.array([2,4,7,4])
print(np.array_equal(array_02, array_03))

False


## Slicing de Array numpy (fatiamento)

In [52]:
array_04 = np.arange(20)
print(array_04)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [53]:
print(array_04[5:15:2])

[ 5  7  9 11 13]


In [54]:
print(array_04[5::])

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
