# 2darray - Array de 2 dimenções

## Aula

In [2]:
import numpy as np

## Criação de um 2darray

In [3]:
# Utiliza também a função array()

array_1 = np.array([[1,2,3], [4,5,6]])

In [4]:
print(array_1)

[[1 2 3]
 [4 5 6]]


In [8]:
print(type(array_1))

<class 'numpy.ndarray'>


## Acessando elementos do Array de 2 dimensões

In [19]:
# sempre na seguencia: linha x coluna. Se usa colchetes[]

# linha 1; coluna 1

print(array_1[1][1])

5


In [13]:
# linha0; coluna2

print(array_1[0][2])

3


In [17]:
# linha0; coluna1

print(array_1[0,1])

2


In [18]:
# Para substituirum valor se utiliza colchetes também

array_1[0][1] = 30
print(array_1)

[[ 1 30  3]
 [ 4  5  6]]


In [20]:
# 

array_1[1,0] = 15
print(array_1)

[[ 1 30  3]
 [15  5  6]]


## Propriedades para 2darray

In [21]:
# shape - retorna a quantidade de elementos por dimensão

print(array_1.shape)

(2, 3)


In [22]:
array_teste = np.array([2,5,6,2,1])
print(array_teste.shape)

(5,)


In [23]:
# size - quantidade total de elementos no array

print(array_1.size)

6


In [24]:
# ndim - retorna oa dimensão do array

print(array_1.ndim)

2


## Funções para 2darray

In [26]:
# cumsum() - soma acumulada

print(array_1.cumsum())

[ 1 31 34 49 54 60]


In [33]:
# reshape - modifica a dimesão do array

# Ex1:
array_d1 = np.array([1,2,3,4,5,6])
print(array_d1.reshape(2,3))

print()

# Ex2:
array_2 = array_d1.reshape(2,3)
print(array_2)

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [32]:
print(array_1.cumsum().reshape(2,3))

[[ 1 31 34]
 [49 54 60]]


In [34]:
'''
A função cumsum() gera um array de 1 dimensão. No exemplo a seguir, foi acumulado
com a função reshape(), que é executado em seguida ferando novamente o array
de duas dimensões.
'''

print(array_1.cumsum().reshape(2,3))

[[ 1 31 34]
 [49 54 60]]


In [39]:
'''
Ao adicionar a propriedade reshape(), 
transforma em um array de 2 dimensões, 
em 5 (cinco) linhas e 2 (duas) colunas
'''

array_3 = np.array(range(1,11))
print(array_3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


Você pode representá-la como um array de 2ª dimensão da seguinte maneira:

In [27]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Aqui, matriz[0] seria a primeira linha [1, 2, 3], matriz[1] seria a segunda linha [4, 5, 6], e assim por diante1.

No Jupyter Notebook, você pode usar a biblioteca NumPy para trabalhar com arrays de múltiplas dimensões. Por exemplo:

In [28]:
import numpy as np

# Criando um array de 2ª dimensão
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
